### PR TITLE
Add Fish 2.3.1 and add some extra packages

### PR DESCRIPTION
**Pull request by sagebind**
Added image for Fish 2.3.1. Also, help text was not working without `nroff` and a few extra commands, so added those to each image.

### CODE REVIEW

**Comment by bpinto** [comment]
:+1:

**Comment by sagebind** [comment]
@bpinto I can merge if you bless me with the power 😉

**Comment by bpinto** [comment]
@coderstephen Done! :D

**Comment by sagebind** [comment]
@bpinto Can you bless me with the power to update the Docker Hub build as well? 💪

**Comment by bpinto** [comment]
How can I do that?

**Comment by sagebind** [comment]
@bpinto You'll have to either add me to the `ohmyfish` Docker Hub account somehow or message me the credentials I think.

**Comment by bpinto** [comment]
@coderstephen I added you to the team, let me know if it works!

**Comment by sagebind** [comment]
@bpinto Yep, that worked. Cool! Merging... :shipit:

**Pull request merged**
